/* Autogenerated by png2wx.pl on Fri Mar 31 17:36:04 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_otidalroute;
extern wxBitmap *_img_otidalroute_pi;

#ifdef OTIDALROUTE_USE_SVG
extern wxString _svg_otidalroute;
extern wxString _svg_otidalroute_rollover;
extern wxString _svg_otidalroute_toggled;
#endif

#endif /* ICONS_H */
